spring:
  application:
    name: tgc-shopping-cart-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: product
logging:
  structured:
    format:
      console: ecs
  level:
    root: info
product:
  topic: product-topic

